/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.24 from the
 * contents of fish_vol_xs.xs. Do not edit this file, edit fish_vol_xs.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "fish_vol_xs.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

/* Not necessary to #include fasound.h.
 * But we want MAX_ constants.
 */

#include "../fasound/fasound.h"

#line 24 "fish_vol_xs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 166 "fish_vol_xs.c"

XS_EUPXS(XS_fish_vol_xs_xs_test); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_test)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 19 "fish_vol_xs.xs"
        //RETVAL = 3;
        XSRETURN_UNDEF;
#line 180 "fish_vol_xs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_init); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_init)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "options");
    {
	int	options = (int)SvIV(ST(0))
;
	AV *	RETVAL;
#line 28 "fish_vol_xs.xs"
        int m = MAX_SOUND_CARDS;
        int n = MAX_ELEMS;
        int o = MAX_FDS;
        const char *card_names_hw[MAX_SOUND_CARDS] = {0};
        const char *card_names_string[MAX_SOUND_CARDS] = {0};
        const char *ctl_names[MAX_SOUND_CARDS][MAX_ELEMS] = {0};
        int fds[MAX_SOUND_CARDS][MAX_FDS] = {0};

        RETVAL = newAV();
        sv_2mortal((SV*)RETVAL);

        if (!asound_interface_init(options, card_names_string, card_names_hw, ctl_names, fds)) {
            XSRETURN_EMPTY; // Just returning newAV() produces (undef), not empty.
        }
        int i, j, k; // not c99
        bool found_one = false;
        for (i = 0; i < m; i++) {
            AV *card_av = newAV();
            const char *card_name_hw = card_names_hw[i];
            if (! card_name_hw)
                continue;
            found_one = true;

            const char *card_name_string = card_names_string[i];
            if (! card_name_string)
                card_name_string = "UNKNOWN";

            SV *card_idx_sv = newSViv(i);
            av_push(card_av, card_idx_sv);

            int size;

            size = strnlen(card_name_hw, MAX_CARD_NAME_HW_SIZE) == MAX_CARD_NAME_HW_SIZE ? MAX_CARD_NAME_HW_SIZE : 0; // 0 means let them do it for us
            SV *card_name_hw_sv = newSVpv(card_name_hw, size);
            av_push(card_av, card_name_hw_sv);

            size = strnlen(card_name_string, MAX_CARD_NAME_STRING_SIZE) == MAX_CARD_NAME_STRING_SIZE ? MAX_CARD_NAME_STRING_SIZE : 0; // 0 means let them do it for us
            SV *card_name_string_sv = newSVpv(card_name_string, size);
            av_push(card_av, card_name_string_sv);

            AV *ctl_av = newAV();
            for (j = 0; j < n; j++) {
                const char *ctl_name = ctl_names[i][j];
                if (! ctl_name) 
                    continue;
                int size = strnlen(ctl_name, MAX_ELEM_NAME_SIZE) == MAX_ELEM_NAME_SIZE ? MAX_ELEM_NAME_SIZE : 0;
                SV *sv = newSVpv(ctl_name, size);
                av_push(ctl_av, sv);
            }
            av_push(card_av, newRV((SV*) ctl_av));
            AV *pollav = newAV();
            for (k = 0; k < 2; k++) {
                int fd = fds[i][k];
                if (!fd) 
                    continue;
                SV *sv = newSViv(fd);
                av_push(pollav, sv);
            }
            av_push(card_av, newRV((SV*) pollav));
            av_push(RETVAL, newRV((SV*) card_av));
        }
        if (!found_one) 
            XSRETURN_EMPTY;
#line 261 "fish_vol_xs.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_set)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "card_idx, ctl_idx, val_perc");
    {
	int	card_idx = (int)SvIV(ST(0))
;
	int	ctl_idx = (int)SvIV(ST(1))
;
	double	val_perc = (double)SvNV(ST(2))
;
	bool	RETVAL;
#line 100 "fish_vol_xs.xs"
        RETVAL = asound_interface_set(card_idx, ctl_idx, val_perc);
#line 285 "fish_vol_xs.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_set_rel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_set_rel)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "card_idx, ctl_idx, delta_perc");
    {
	int	card_idx = (int)SvIV(ST(0))
;
	int	ctl_idx = (int)SvIV(ST(1))
;
	int	delta_perc = (int)SvIV(ST(2))
;
	bool	RETVAL;
#line 110 "fish_vol_xs.xs"
        RETVAL = asound_interface_set_rel(card_idx, ctl_idx, delta_perc);
#line 308 "fish_vol_xs.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_update); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_update)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "card_idx, ctl_idx");
    {
	int	card_idx = (int)SvIV(ST(0))
;
	int	ctl_idx = (int)SvIV(ST(1))
;
	bool	RETVAL;
#line 119 "fish_vol_xs.xs"
        bool changed;
        if (!asound_interface_update(card_idx, ctl_idx, &changed))
            XSRETURN_UNDEF;
        RETVAL = changed;
#line 332 "fish_vol_xs.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_get)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "card_idx, ctl_idx");
    {
	int	card_idx = (int)SvIV(ST(0))
;
	int	ctl_idx = (int)SvIV(ST(1))
;
	double	RETVAL;
	dXSTARG;
#line 131 "fish_vol_xs.xs"
        double val;
        /* man perlcall
         */
        if (!asound_interface_get(card_idx, ctl_idx, &val)) 
            XSRETURN_UNDEF;
        RETVAL = val;
#line 359 "fish_vol_xs.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_finish); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_finish)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	bool	RETVAL;
#line 143 "fish_vol_xs.xs"
        RETVAL = asound_interface_finish();
#line 376 "fish_vol_xs.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_fish_vol_xs_xs_handle_event); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fish_vol_xs_xs_handle_event)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "card_num");
    {
	int	card_num = (int)SvIV(ST(0))
;
	bool	RETVAL;
#line 151 "fish_vol_xs.xs"
        RETVAL = asound_interface_handle_event(card_num);
#line 395 "fish_vol_xs.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_fish_vol_xs); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_fish_vol_xs)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("fish_vol_xs::xs_test", XS_fish_vol_xs_xs_test, file);
        newXS("fish_vol_xs::xs_init", XS_fish_vol_xs_xs_init, file);
        newXS("fish_vol_xs::xs_set", XS_fish_vol_xs_xs_set, file);
        newXS("fish_vol_xs::xs_set_rel", XS_fish_vol_xs_xs_set_rel, file);
        newXS("fish_vol_xs::xs_update", XS_fish_vol_xs_xs_update, file);
        newXS("fish_vol_xs::xs_get", XS_fish_vol_xs_xs_get, file);
        newXS("fish_vol_xs::xs_finish", XS_fish_vol_xs_xs_finish, file);
        newXS("fish_vol_xs::xs_handle_event", XS_fish_vol_xs_xs_handle_event, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

